### ISSUE TITLE
Empty tests generated for an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/EvoCrash#13]
#### Characteristics
- **Issue Type**: possible bug/missuse
- **Reproducibility**: always
- **Tool/Service/Component**: EvoCrash
- **Execution Environment**: Linux Ubuntu
- **Reporter**: Ricardo José Tejada <ricardo.tejada.external@atos.net>

#### Description

EvoCrash generates the tests for a simple class that produces an ArrayIndexOutOfBoundsException,
but they are empty and the following Gradle tasks after test generation take an extremely long time.

The terminal shows this output

![terminal](https://user-images.githubusercontent.com/36235771/43318264-93b513fc-918f-11e8-8302-b61c7662a93c.png)

#### Steps to reproduce

Create the following class

![class](https://user-images.githubusercontent.com/36235771/43316319-7cd9b78e-9188-11e8-911c-f3dbf674af50.png)

Put it in a jar, get it's log file, put the jar and the log file in the EvoCrash-Demo project and modify config.properties

![files](https://user-images.githubusercontent.com/36235771/43316813-0ac7a3a2-918a-11e8-8770-1a602d22164f.png)

![properties](https://user-images.githubusercontent.com/36235771/43316816-0e51c110-918a-11e8-9ee6-71167a745f4b.png)

Finally go to Demo folder and execute ./gradlew run

#### Other files and URLs

In Files.zip you can find: HelloException.jar, the log file, and the empty test produced by EvoCrash

[Files.zip](https://github.com/STAMP-project/EvoCrash/files/2235553/Files.zip)

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by RicardoTej** [comment]
Good morning :

I have tried using another simple jar that produces a 3 levels exception,
it is a class cast exception like the one of the demo,
and I have the same problem.

furthermore the final task, run, produces an exception.

in the zip folder you can find :
the trace, the jar, the jar's project, the config.properties and the .log file used in the experiment.
[30-8.zip](https://github.com/STAMP-project/EvoCrash/files/2336020/30-8.zip)

**Comment by pderakhshanfar** [comment]
Hello Ricardo,

According to the output that you sent, the search process has started (the texts like "currentFitness: 3.0" are showing the progress of the search process), and it finished the search (in output: "GGA was done in 601"). However, it could not achieve the crash reproduction. It is because of the complexity of some cases. The options that you have here are 1- increasing the search budget (search.budget in config.properties) 2- rerun the process for a couple of times with same budget (due to the randomness it is possible that EvoCrash can achieve to the crash reproduction faster) 3- trying the crash reproduction in different frame level (changing frame.level in config.properties)

**Comment by jesus-gorronogoitia** [comment]
Hi Puria, 
I've reproduced the problem Ricardo has faced, getting same results. I am a big surprise that this extremely toy-software (only two classes) could be considered complex by Evocrash. We decided to test it first with an very simple test software showing a crash exception in order to get familiarized with the tool, before proceeding with real industrial software. 
Following your advice, I've run Evocrash several times, getting the same negative results. I've also reduced the frame-level, set to 2 (instead of 3) with the same negative result. Now, I will try to increase the current budget (600) to 1000. I will let you know the results, but I wonder what makes this very simple crashing software so complex that Evocrash fails.

Btw, I also noticed that Evocrash demo gets stuck after computation, showing 75% of progress in Gradle console:

```
* Computation finished
Exception in thread "main" java.lang.AssertionError: expected:<0.0> but was:<3.0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:553)
        at org.junit.Assert.assertEquals(Assert.java:683)
        at eu.stamp_project.evocrash.demo.TestCreation.create(TestCreation.java:97)
        at eu.stamp_project.evocrash.demo.Application.main(Application.java:6)
> Building 75% > :run
```
so I have to stop it with ctrl-c

**Comment by jesus-gorronogoitia** [comment]
Hi Puria,
Even with a budget of 1000, Evocrash fails on finding a crash replicating test for this simple case. Any idea how to proceed with this example? Do you need additional information for your analysis?

**Comment by jesus-gorronogoitia** [comment]
Inspecting build.gradle I realized that the dependencies section included references to the folders where the libraries for XWiki and ActiveEon systems where placed, so I added the corresponding entry for Atos testing example we are using in this initial report:
`testCompile fileTree(dir: 'src/resources/targetedSoftware/Atos', include: '*.jar')`
However the results are the same, so this Gradle configuration seems not to have effect on Evocrash execution.

**Comment by jesus-gorronogoitia** [comment]
@pderakhshanfar I've created a completely different crashing code (as PoC) for testing Evocrash that produces a NPE. When I apply Evocrash, with framelevels 2 or 1, I still get the same unsuccessful results reported in this issue.
I attach, project source code (.zip), log file, config.properties.

I wonder why Evocrash cannot reproduce this very simple crash (in a very simple code). Could we have @pderakhshanfar a virtual meeting  to analyse this case?
[AtosPoC4Evocrash.zip](https://github.com/STAMP-project/EvoCrash/files/2352586/AtosPoC4Evocrash.zip)
[AtosCrashPoC2.log](https://github.com/STAMP-project/EvoCrash/files/2352589/AtosCrashPoC2.log)
[AtosPoC4Evocrash.jar.zip](https://github.com/STAMP-project/EvoCrash/files/2352599/AtosPoC4Evocrash.jar.zip)

**Comment by pderakhshanfar** [comment]
@jesus-gorronogoitia @RicardoTej I am sorry, I just tried to run EvoCrash with your toy cases. I found the problem. In the log file, you should just put the stack trace. For instance, in HelloExceptionLog.log file you should put only:

java.lang.ArrayIndexOutOfBoundsException: 1
	at hello.exception.HelloException.main(HelloException.java:8)

Also, for AtosCrashPoC2.log you should put:
java.lang.NullPointerException
	at eu.stamp.uc.atos.evocrash.poc2.BookShop.reduceStockByAmount(BookShop.java:15)
	at eu.stamp.uc.atos.evocrash.poc2.BookShop.purchaseBook(BookShop.java:11)
	at eu.stamp.uc.atos.evocrash.poc2.BookShopApplication.main(BookShopApplication.java:7)


I applied EvoCrash to AtosCrashPoC2, and It can reproduce all of the frames of the crash in less than a second.

**Comment by jesus-gorronogoitia** [comment]
@pderakhshanfar thanks a lot!! 
Please, improve the documentation explaining how stack trace should be reported, because, strictly speaking, the former stack trace we reported was exactly as the JVM output.

**Comment by jesus-gorronogoitia** [comment]
I confirm it works for me in Linux. Please @RicardoTej fix it in your case and try it out in Windows.

**Comment by pderakhshanfar** [comment]
@jesus-gorronogoitia Currently, we are doing a general refactoring on our approach. It will be more user-friendly and more powerful. We will update the documentation as soon as we have the refactored tool.

**Comment by jesus-gorronogoitia** [comment]
@pderakhshanfar Perfect!, take your time. Please, keep us informed.
Meantime,  we will be working on the Eclipse plugin for Evocrash using the Gradle approach you use for Evocrash Demo. 

Should we wait for you to complete this refactoring before working on the Eclipse plugin, because the Evocrash configuration/execution will eventually change significantly, or not?

Please confirm the approach reported in #17 for executing Evocrash from latest source/binaries is correct.
